# ===============================================
# SERVER & SWAGGER CONFIGURATION
# ===============================================
server:
  port: 8080
  servlet:
    context-path: /api/v1

springdoc:
  info:
    title: Currency API Demo
    description: 完整的 API 檔案，包含幣別資料的 CRUD 操作與 Coindesk 資料轉換服務。
    version: 1.0.0
  swagger-ui:
    enabled: true
    title: API 檔案 | Currency Demo
  api-docs:
    path: /api-docs

# ===============================================
# DATABASE & EXTERNAL API CONFIGURATION
# ===============================================
spring:
  application:
    name: currency-api

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

# ===============================================
# EXTERNAL API CONFIGURATION
# ===============================================

coindesk:
  api:
    url: https://kengp3.github.io/blog/coindesk.json
    timeout: 5000
    retry-count: 3

# ===============================================
# LOGGING CONFIGURATION
# ===============================================
logging:
  level:
    io.github.montytsai: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# ===============================================
# MANAGEMENT & ACTUATOR
# ===============================================
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always