DROP TABLE IF EXISTS CURRENCY;

CREATE TABLE CURRENCY (
    code VARCHAR(10) PRIMARY KEY,
    display_name VARCHAR(50) NOT NULL,
    symbol VARCHAR(10),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);